name: Validate and Deploy to Salesforce on ST Merge

on:
  push:
    branches:
      - ST

jobs:
  validate-and-deploy:
    name: Validate and Deploy to Salesforce
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0" 
    

      # Step 3: Install Salesforce CLI
      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1


      # Step 5: Authenticate to Salesforce Org
      - name: Authenticate to Salesforce Org
        run: |
          echo "Authenticating to Salesforce Org..."
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sf org login jwt   --client-id "${{ secrets.SF_CLIENT_ID }}" \
                             --jwt-key-file server.key \
                             --username "${{ secrets.SF_USERNAME }}" \
                             --instance-url "${{ secrets.SF_INSTANCE_URL }}" \
                             --alias "${{ secrets.SF_ORG_ALIAS }}"
        env:
          SF_JWT_KEY: ${{ secrets.SF_JWT_KEY }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
          SF_ORG_ALIAS: ${{ secrets.SF_ORG_ALIAS }}
          SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}


      # Step 7: Validate Deployment (Dry Run)
      - name: Validate Deployment
        run: |
          sfdx force:source:deploy -p force-app -u "${{ secrets.SF_ORG_ALIAS }}" --checkonly --testlevel RunLocalTests --wait 10

      # Step 8: Perform Actual Deployment (If Validation Succeeds)
      - name: Perform Deployment
        run: |
          sfdx force:source:deploy force-app -u "${{ secrets.SF_ORG_ALIAS }}" --testlevel RunLocalTests --wait 10